CREATE DATABASE nyc_crashes;
USE nyc_crashes;

CREATE TABLE `collisions` (
  `COLLISION_ID` bigint NOT NULL,
  `CRASH_DATE` date DEFAULT NULL,
  `CRASH_TIME` time DEFAULT NULL,
  `BOROUGH` varchar(100) DEFAULT NULL,
  `ZIP_CODE` varchar(10) DEFAULT NULL,
  `LATITUDE` double DEFAULT NULL,
  `LONGITUDE` double DEFAULT NULL,
  `ON_STREET_NAME` text,
  `CROSS_STREET_NAME` text,
  `OFF_STREET_NAME` text,
  `NUMBER_OF_PERSONS_INJURED` int DEFAULT NULL,
  `NUMBER_OF_PERSONS_KILLED` int DEFAULT NULL,
  `NUMBER_OF_PEDESTRIANS_INJURED` int DEFAULT NULL,
  `NUMBER_OF_PEDESTRIANS_KILLED` int DEFAULT NULL,
  `NUMBER_OF_CYCLIST_INJURED` int DEFAULT NULL,
  `NUMBER_OF_CYCLIST_KILLED` int DEFAULT NULL,
  `NUMBER_OF_MOTORIST_INJURED` int DEFAULT NULL,
  `NUMBER_OF_MOTORIST_KILLED` int DEFAULT NULL,
  `HOUR` int DEFAULT NULL,
  `YEAR` int DEFAULT NULL,
  `MONTH` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`COLLISION_ID`)
);